### ISSUE TITLE
Bronvermelding

### ISSUE THREAD

**Issue by dhvenema** [Geonovum/whitepaper-standaarden#17]
Momenteel is de Bibliografie incompleet. Voor gebruikers zou het beter zijn als alle bronnen die gebruikt worden, ook worden verwezen in de bibliografie en in de tekst. Dit kan verwerkt worden in de [config.js](https://github.com/Geonovum/whitepaper-standaarden/blob/gh-pages/js/config.js) op basis van een [localBiblio](https://github.com/w3c/respec/wiki/localBiblio). Op de [specref rep](https://github.com/tobie/specref/blob/master/schemas/raw-reference.json) staat de gehele JSON-scheme voor referenties. Deze [tool ](https://marcoscaceres.github.io/bib_entry_maker/)is handig om referenties te maken volgens ReSpec. Bijv.:
```javascript
var respecConfig = {
  localBiblio: {
    "ISO19101": {
      "href": "https://www.iso.org/standard/26002.html",
      "title": "ISO 19101:2002 Geographic information -- Reference model",
      "authors": [""],
      "date": "Juli 2002",
      "publisher": "International Organization for Standardization",
    },
  },
};
```
Deze bronnen kan je vervolgens aanhalen in je tekst via:
```html
<a data-cite="ISO19101">ISO 19101:2002</a>
```

**Comment by lvdbrink** [comment]
Volgens mij kun je ook deze notatie in de tekst gebruiken: [[ISO19101]]
