### ISSUE TITLE
Scope issue

### ISSUE THREAD

**Issue by frisopenninga** [Geonovum/whitepaper-standaarden#4]
Hoewel nergens expliciet gedefinieerd, lijkt de huidige set geostandaarden zich volledig te richten op vectordata. Dit roept vragen op:
- moeten we de scope van de huidige set expliciet vastleggen?
- moet de scope van de toekomstige set verbreden met o.a. raster en pointcloud data?
- in hoeverre moeten en kunnen we in deze white paper al ontwikkelingen rond niet-vectordata schetsen?

**Comment by thijsbrentjens** [comment]
Veel standaarden gaan over vectordata inderdaad, maar rasterdata kunnen via de set standaarden ook ontsloten worden. Denk aan WMS profiel voor bijvoorbeeld luchtfoto's of andere rasters. 
We hebben geen Nederlands WCS profiel, daar leek/lijkt weinig noodzaak toe. Binnen INSPIRE wordt WCS sinds kort wel gezien als een download service, http://inspire.ec.europa.eu/id/document/tg/download-wcs. In die zin zijn er wel wat standaarden voor rasterdata.

Voor pointclouds: kan dat via 3D aangestipt worden?

En via metadata kunnen we natuurlijk ook rasterdata beschrijven.

Het is misschien goed om in de scope wel iets op te nemen over deze discussie. Al is het maar benoemen dat de set standaarden sterk gericht is op vectordata, maar andere structuren (laat ik het zo maar even noemen) wel degelijk aan bod komen.

**Comment by Naisunev** [comment]
geostandaarden hebben hun historie in rasterdata... toen was vectordata hip omdat dit in tegenstelling tot rasterdata bruikbaarder is in veel gevallen. de trend lijkt nu richting 3d/pointcloud data te gaan. Denk ook aan b.v. BIM modellen voor gebouwen in combinatie met self-driving cars met camera beelden en 3d point clouds. Wanneer je dat ook afzet tegen project Tango van Google met Visual Positioning System en augmented reality dan ligt er nog veel in het verschiet

Qua scope vind ik het interessant om het af te zetten tegen: wie is nu de doelgroep, en wie verwachten we dat de volgende doelgroep wordt? Daarnaast zou ik het document afzetten tegen wat er op het internet gebruikt wordt en hoe de wederzijdse adoptie van zaken zijn. Vaak loopt het internet voor op wat er gestandaardiseerd beschikbaar is.

**Comment by wisze** [comment]
Als het Copernicus programma tot een doorbraak van satellietdata leidt komt de vraag naar standaardisering van rasterbeelden vanzelf. Het is handig om de processing historie van een beeld op een standaard manier te beschrijven evenals de classificatie en onzekerheid van de rasterpixels.

**Comment by lvdbrink** [comment]
Zie ook #22

**Comment by frisopenninga** [comment]
Er is niet direct aanleiding om de scope expliciet vast te leggen, maar wel om de set in de praktijk te verbreden. Hoewel de huidige set zich niet volledig tot vectordata beperkt, signaleren we wel degelijk open vraagstukken rond o.a. pointclouds en rasterdata. In algemenere zin adresseren we dit in de definitieve versie van de white paper als het Observations and measurements domein, waarin data in coverages worden vastgelegd. Hiermee komen domeinen als hydrografie, meteorologie en de ondergrond nadrukkelijker in beeld. 

Het domein Observations and measurements kan ook gezien worden als eerste stap in de opkomst van de sensoren. Veel data uit O&M-hoek in te danken aan doorbraken op het gebied van inwintechnologie (oa. LIDAR). Op het moment dat die technologie steeds bereikbaarder wordt voor niet-specialisten en niet alleen in traditionele inwin-context wordt toegepast (maar bijv. i.h.k.v. Smart Cities) komt het sensordomein in beeld. 

Qua context richt Geonovum zich voorlopig op de data die echt in de SDI terecht komt (gevalideerd, voor hergebruik bedoeld, 'kwaliteit gegarandeerd door de overheid') en niet zozeer op allerlei ruwe datastromen uit individuele sensoren.
