### ISSUE TITLE
Open world assumption

### ISSUE THREAD

**Issue by frisopenninga** [Geonovum/whitepaper-standaarden#5]
Moet NEN3610 expliciet uitgaan van de open world assumption?

**Comment by wisze** [comment]
Ik begreep uit de presentaties op de Geonovum dag dat een closed world assumption nodig is om gegevens te kunnen valideren tegen een informatiemodel. Een open world assumption geeft de gegevensbeheerder veel vrijheid in het uitbreiden buiten een gegevensstandaard. Bij het IHW beheren we het Aquo model en zijn afhankelijk van valide gegevens van de waterbeheerders om de EU rapportages te maken. Valideren tegen een schema is dus echt nodig.
Dan is dus een closed world assumption nodig. Maar corrigeer me als ik iets verkeerd begrepen heb!

**Comment by PalmJanssen** [comment]
Als we met open world assumption bedoelen: Anybody can say anything about anything. Dan is dat niet wat in de meeste gevallen met NEN 3610 modellen wordt beoogd. Het is eerder zoals hierboven aangegeven dat de modellen zijn ontwikkeld om de berichten interoperabel te kunnen uitwisselen, met een consensus over semantiek en structuur. Het is dus een 'gecontroleerde omgeving' met daarbij behorende validaties. Dus het model bepaalt wat en hoe je het kan zeggen. Je zou dus bijna eerder het tegenovergestelde kunnen zeggen: NEN 3610 gaat uit van een closed world assumption.

**Comment by NielsHoffmann** [comment]
De discussie OWA/CWA is precies de discussie tussen basisregistraties en 'het internet'.
Een basisregistratie wil met een grote mate van zekerheid vastleggen hoe de wereld in elkaar zit, terwijl andere datasets gebaseerd kunnen zijn op aannames, incomplete data etc. etc.

Ik denk dat er voor het stelsel van basisregistraties (en de NEN3610 staat daar aan de bron van) een implementatie moet komen op basis van een closed world assumption. Is Shacl hier de richting voor die we uit moeten denken?

**Comment by frisopenninga** [comment]
Op het semantisch web is het gebruikelijk om uit te gaan van de 'open world assumption', waarmee de linkbaarheid maximaal is. Dat rechtvaardigt de vraag of het niet wenselijk -of wellicht zelfs noodzakelijk- is om dit als uitgangspunt bij NEN3610 in te brengen. We kiezen er nu echter bewust voor om dat niet te doen en daarmee uit te blijven gaan van de closed world assumption van NEN3610. De belangrijkste overweging hierbij is dat de closed world assumption validatie mogelijk maakt. En omdat juist in een SDI betrouwbare en juiste overheidsdata centraal staat, is valideren een must. Daarom kiezen we er voor om NEN3610 zelf intact te laten en met een Linked Data-profiel de linkbaarheid te vergroten.
