### ISSUE TITLE
NL-profiel op GeoSPARQL?

### ISSUE THREAD

**Issue by frisopenninga** [Geonovum/whitepaper-standaarden#7]
Voor aanbieders van webservices kennen we in Nederland profielen die aanvullende eisen stellen (o.a. rond coördinaatsystemen) en voor aanbieders van API's zien we dat de API-strategieën iets vergelijkbaars doen. Dat roept de vraag op in hoeverre het noodzakelijk of wenselijk is om ook op OGC GeoSPARQL aanvullende eisen te definiëren in een Nederlands profiel.

**Comment by NielsHoffmann** [comment]
Wat mij betreft is de GeoSPARQL standaard nog zo nieuw dat het nog onduidelijk is hoe de ontwikkeling ervan zal lopen. Ik zie de meerwaarde van een NL-profiel om bijv. RD voor te schrijven/ondersteunen.

Maar tegelijkertijd vraag ik me af hoe groot de beschikbaarheid van (Geo)SPARQL-endpoints zal gaan worden. Het feit dat je (net als met 'gewoon'  SQL) alle willekeurige vragen aan je dataset kan stellen en daarmee potentieel de service bijzonder zwaar kan belasten maakt het een kwetsbare interface. 
Ik denk dat we misschien veel meer richting een standaard rest-api specificatie moeten gaan denken om triple stores te bevragen.

**Comment by lvdbrink** [comment]
Zie ook #24

**Comment by frisopenninga** [comment]
Op dit moment zien we bij het werkveld nog geen behoefte aan een Nederlands profiel op GeoSPARQL of aan het toevoegen aan de set Geostandaarden op de Pas toe of leg uit-lijst.
